services:
  srv-masterproxy:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "com.networksintelligence.app=${APP_ID}"
        - "com.networksintelligence.service=${SERVICE_ID}"
    ports:
      - ${PORT_FTD}:81
      - ${PORT_HTTP}:80
      - ${PORT_HTTPS}:443
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - data:/data
      - letsencrypt:/etc/letsencrypt
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://masterlogs.networksintelligence.com:12201"
        tag: "srv-proxy"
    environment:
      OTLP_HTTP_ENDPOINT: "https://masterlogs.networksintelligence.com/api/default"
      OTLP_HTTP_AUTHORIZATION: "Basic d2VibWFzdGVyQG5ldHdvcmtzaW50ZWxsaWdlbmNlLmNvbTpjcmdKWmtmWkhMQXZ1RGl6"
    networks:
      networksintelligence_com:
        ipv4_address: 172.23.0.10

  wireguard-master:
    image: 'linuxserver/wireguard'
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker
      labels:
        - "com.networksintelligence.app=${APP_ID}"
        - "com.networksintelligence.service=${SERVICE_ID}${MICROSERVICE_ID}${MICROSERVICE_VERSION}"
    ports:
      - "51820:51820/udp"     
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /lib/modules:/lib/modules:ro 
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - wireguard_config:/config
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    networks:
      networksintelligence_com:
        ipv4_address: 172.23.0.50

networks:
  networksintelligence_com:
    external: true
    labels:
      - "com.networksintelligence.app=${APP_ID}"
      - "com.networksintelligence.type=application"

volumes:
  data:
    name: ${APP_ID}${SERVICE_ID}${MICROSERVICE_ID}${MICROSERVICE_VERSION}_data
    driver: local
    labels:
      - "com.networksintelligence.app=${APP_ID}"
      - "com.networksintelligence.type=data"
  letsencrypt:
    name: ${APP_ID}${SERVICE_ID}${MICROSERVICE_ID}${MICROSERVICE_VERSION}_letsencrypt
    driver: local
    labels:
      - "com.networksintelligence.app=${APP_ID}"
      - "com.networksintelligence.type=cert"
  wireguard_config:
    name: ${APP_ID}${SERVICE_ID}${MICROSERVICE_ID}${MICROSERVICE_VERSION}_wireguard
    driver: local
    labels:
      - "com.networksintelligence.app=${APP_ID}"
      - "com.networksintelligence.type=config"