services:
  proxy:
    image: 'jc21/nginx-proxy-manager:latest'

    ports:
      - target: 81
        published: ${PORT_FTD}
        protocol: tcp
        mode: host
      - target: 80
        published: ${PORT_HTTP}
        protocol: tcp
        mode: host
      - target: 443
        published: ${PORT_HTTPS}
        protocol: tcp
        mode: host
    volumes:
      - proxy_data:/data
      - proxy_letsencrypt:/etc/letsencrypt
    environment:
      - DISABLE_IPV6=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:81"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "com.networksintelligence.app=${APP_ID}"
        - "com.networksintelligence.type=proxy"
      update_config:
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    networks:
      decentra:
        ipv4_address: 192.168.123.10



networks:
  decentra:
    driver: overlay
    attachable: true
    driver_opts:
      encrypted: "true"
    ipam:
      config:
        - subnet: 192.168.123.0/24

volumes:
  proxy_data:
    name: ${APP_ID}${SERVICE_ID}${MICROSERVICE_ID}${MICROSERVICE_VERSION}_masterproxy_data
    driver: local
  proxy_letsencrypt:
    name: ${APP_ID}${SERVICE_ID}${MICROSERVICE_ID}${MICROSERVICE_VERSION}_masterproxy_letsencrypt
    driver: local